[2024-06-28 10:07:36,939: INFO: main: my first log dfor check]
[2024-06-28 10:09:35,014: INFO: main: my first log for check]
[2024-06-28 12:53:20,662: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 12:53:20,752: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 12:53:20,756: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 12:53:20,759: INFO: common: created directory at: artifacts]
[2024-06-28 12:53:20,762: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 12:56:01,711: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 12:56:01,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 12:56:01,716: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 12:56:01,718: INFO: common: created directory at: artifacts]
[2024-06-28 12:56:01,720: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 12:56:48,291: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 12:56:48,294: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 12:56:48,296: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 12:56:48,297: INFO: common: created directory at: artifacts]
[2024-06-28 12:56:48,298: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 12:56:49,386: INFO: 3351880409: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 267815
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "fcf4e6e192bd02a6bf9d98ce1f322f865e4eca3980bccff3ea196f83b780509f"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: CD02:FD28B:29A6:3172:667E65B8
Accept-Ranges: bytes
Date: Fri, 28 Jun 2024 07:26:49 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10242-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1719559609.965152,VS0,VE318
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4b87a8846f6fc1c8d1b765c8061936bd3615eba9
Expires: Fri, 28 Jun 2024 07:31:49 GMT
Source-Age: 0

]
[2024-06-28 14:07:55,562: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 14:07:55,566: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 14:07:55,568: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 14:07:55,569: INFO: common: created directory at: artifacts]
[2024-06-28 14:07:55,571: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 14:07:55,572: INFO: 3351880409: File already exists of size: ~ 262 KB]
[2024-06-28 14:08:18,289: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 14:08:18,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 14:08:18,294: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 14:08:18,296: INFO: common: created directory at: artifacts]
[2024-06-28 14:08:18,298: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 14:15:17,836: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 14:15:17,838: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 14:15:17,841: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 14:15:17,842: INFO: common: created directory at: artifacts]
[2024-06-28 14:15:17,845: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 14:15:18,877: INFO: 3351880409: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 27261
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "441631a9e78ca1e74f8457f3690e9294a49ba8c958be1ac1c4716adda595acd9"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5077:E13C:201F1A:2721AE:667E781A
Accept-Ranges: bytes
Date: Fri, 28 Jun 2024 08:45:18 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10220-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1719564319.575684,VS0,VE312
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6a8a540efb1e657f4e9b90172ad6542f54d6e921
Expires: Fri, 28 Jun 2024 08:50:18 GMT
Source-Age: 0

]
[2024-06-28 14:46:02,919: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 14:46:02,920: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 14:46:02,921: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 14:46:02,921: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 14:46:02,921: INFO: common: created directory at: artifacts]
[2024-06-28 14:46:02,922: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 14:46:02,922: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-06-28 14:46:02,923: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 14:47:51,761: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 14:47:51,762: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 14:47:51,762: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 14:47:51,763: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 14:47:51,763: INFO: common: created directory at: artifacts]
[2024-06-28 14:47:51,763: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 14:47:52,676: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 27261
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "441631a9e78ca1e74f8457f3690e9294a49ba8c958be1ac1c4716adda595acd9"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5077:E13C:201F1A:2721AE:667E781A
Accept-Ranges: bytes
Date: Fri, 28 Jun 2024 09:17:52 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10241-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1719566272.410469,VS0,VE284
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8694d3c6d95f961550995a30e43e113a81370589
Expires: Fri, 28 Jun 2024 09:22:52 GMT
Source-Age: 0

]
[2024-06-28 14:47:52,678: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 16:54:19,637: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 16:54:19,783: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 16:54:19,787: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 16:54:19,789: INFO: common: created directory at: artifacts]
[2024-06-28 16:54:19,791: INFO: common: created directory at: artifacts/data_validation]
[2024-06-28 17:09:47,937: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 17:09:47,939: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 17:09:47,939: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 17:09:47,942: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 17:09:47,942: INFO: common: created directory at: artifacts]
[2024-06-28 17:09:47,942: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-28 17:09:49,306: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 27261
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "441631a9e78ca1e74f8457f3690e9294a49ba8c958be1ac1c4716adda595acd9"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 526B:C995:237641:2B0012:667EA104
Accept-Ranges: bytes
Date: Fri, 28 Jun 2024 11:39:49 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10243-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1719574789.815719,VS0,VE338
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3b27f2b27bd4a1ad3973d3e4aae7571dd7462868
Expires: Fri, 28 Jun 2024 11:44:49 GMT
Source-Age: 0

]
[2024-06-28 17:09:49,315: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 17:09:49,315: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-06-28 17:09:49,323: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-28 17:09:49,325: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 17:09:49,333: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-28 17:09:49,334: INFO: common: created directory at: artifacts]
[2024-06-28 17:09:49,335: INFO: common: created directory at: artifacts/data_validation]
[2024-06-28 17:09:49,352: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-02 10:40:32,915: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 10:40:33,096: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 10:40:33,143: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 10:40:33,145: INFO: common: created directory at: artifacts]
[2024-07-02 10:40:33,146: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 10:41:19,287: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 10:41:19,290: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 10:41:19,295: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 10:41:19,297: INFO: common: created directory at: artifacts]
[2024-07-02 10:41:19,298: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 10:46:37,286: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 10:46:37,289: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 10:46:37,293: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 10:46:37,295: INFO: common: created directory at: artifacts]
[2024-07-02 10:46:37,300: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 11:00:19,946: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 11:00:19,948: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 11:00:19,953: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 11:00:19,955: INFO: common: created directory at: artifacts]
[2024-07-02 11:00:19,956: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 11:02:56,549: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 11:02:56,553: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 11:02:56,557: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 11:02:56,558: INFO: common: created directory at: artifacts]
[2024-07-02 11:02:56,560: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 11:03:46,074: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 11:03:46,082: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 11:03:46,099: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 11:03:46,104: INFO: common: created directory at: artifacts]
[2024-07-02 11:03:46,108: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 11:03:46,122: ERROR: 1421303987: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_8755/1421303987.py", line 196, in train_test_splitting
    X, y = self.preprocess_data(data)
AttributeError: 'DataTransformation' object has no attribute 'preprocess_data'. Did you mean: 'preprocessor'?
[2024-07-02 11:04:10,293: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 11:04:10,296: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 11:04:10,302: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 11:04:10,304: INFO: common: created directory at: artifacts]
[2024-07-02 11:04:10,307: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 11:04:10,594: ERROR: 3398564310: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_8755/3398564310.py", line 196, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_8755/3398564310.py", line 168, in preprocess_data
    data = self._handle_missing_values(data)
  File "/tmp/ipykernel_8755/3398564310.py", line 44, in _handle_missing_values
    data = data.dropna(subset=[self.config.target_column])
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-07-02 11:23:55,057: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-02 11:23:55,061: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-02 11:23:55,066: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-02 11:23:55,067: INFO: common: created directory at: artifacts]
[2024-07-02 11:23:55,068: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-02 11:23:55,076: ERROR: 2010096920: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_8755/2010096920.py", line 197, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_8755/2010096920.py", line 169, in preprocess_data
    data = self._handle_missing_values(data)
  File "/tmp/ipykernel_8755/2010096920.py", line 45, in _handle_missing_values
    data = data.dropna(subset=[self.config.target_column])
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-07-06 23:23:05,872: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:23:06,057: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:23:06,106: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:23:06,108: INFO: common: created directory at: artifacts]
[2024-07-06 23:23:06,111: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:23:06,250: ERROR: 2010096920: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/2010096920.py", line 197, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/2010096920.py", line 169, in preprocess_data
    data = self._handle_missing_values(data)
  File "/tmp/ipykernel_7478/2010096920.py", line 45, in _handle_missing_values
    data = data.dropna(subset=[self.config.target_column])
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-07-06 23:25:24,804: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:25:24,807: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:25:24,815: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:25:24,817: INFO: common: created directory at: artifacts]
[2024-07-06 23:25:24,819: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:25:24,832: ERROR: 2408568821: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/2408568821.py", line 198, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/2408568821.py", line 169, in preprocess_data
    data = self._handle_missing_values(data)
  File "/tmp/ipykernel_7478/2408568821.py", line 45, in _handle_missing_values
    data = data.dropna(subset=[self.config.target_column])
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-07-06 23:28:00,152: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:28:00,154: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:28:00,162: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:28:00,163: INFO: common: created directory at: artifacts]
[2024-07-06 23:28:00,164: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:28:00,176: ERROR: 98330458: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/98330458.py", line 199, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/98330458.py", line 169, in preprocess_data
    print("CHECK DATAFRAME ",data.columns)
AttributeError: 'NoneType' object has no attribute 'columns'
[2024-07-06 23:30:08,541: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:30:08,544: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:30:08,549: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:30:08,551: INFO: common: created directory at: artifacts]
[2024-07-06 23:30:08,554: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:30:08,567: ERROR: 471311298: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/471311298.py", line 200, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/471311298.py", line 171, in preprocess_data
    data = self._drop_irrelevant_columns(data)
  File "/tmp/ipykernel_7478/471311298.py", line 32, in _drop_irrelevant_columns
    print(data.head())
AttributeError: 'NoneType' object has no attribute 'head'
[2024-07-06 23:32:04,449: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:32:04,453: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:32:04,458: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:32:04,459: INFO: common: created directory at: artifacts]
[2024-07-06 23:32:04,460: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:32:04,561: ERROR: 763822088: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/763822088.py", line 202, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/763822088.py", line 174, in preprocess_data
    data = self._handle_missing_values(data)
  File "/tmp/ipykernel_7478/763822088.py", line 50, in _handle_missing_values
    data = data.dropna(subset=[self.config.target_column])
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-07-06 23:34:05,320: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:34:05,323: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:34:05,327: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:34:05,328: INFO: common: created directory at: artifacts]
[2024-07-06 23:34:05,330: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:34:05,341: ERROR: 2766369880: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/2766369880.py", line 202, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/2766369880.py", line 174, in preprocess_data
    data = self._handle_missing_values(data)
  File "/tmp/ipykernel_7478/2766369880.py", line 50, in _handle_missing_values
    data = data.dropna(subset=[self.config.target_column])
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-07-06 23:35:26,671: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:35:26,673: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:35:26,678: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:35:26,679: INFO: common: created directory at: artifacts]
[2024-07-06 23:35:26,682: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:35:26,711: ERROR: 341168565: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/341168565.py", line 203, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/341168565.py", line 177, in preprocess_data
    X = self._apply_target_encoding(X, y if fit else None, fit=fit)
TypeError: DataTransformation._apply_target_encoding() got an unexpected keyword argument 'fit'
[2024-07-06 23:36:39,566: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:36:39,568: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:36:39,572: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:36:39,574: INFO: common: created directory at: artifacts]
[2024-07-06 23:36:39,575: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:36:39,587: ERROR: 3939069024: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/3939069024.py", line 202, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_7478/3939069024.py", line 176, in preprocess_data
    X = self._apply_target_encoding(X, y if fit else None, fit=fit)
TypeError: DataTransformation._apply_target_encoding() got an unexpected keyword argument 'fit'
[2024-07-06 23:40:49,192: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:40:49,195: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:40:49,199: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:40:49,202: INFO: common: created directory at: artifacts]
[2024-07-06 23:40:49,205: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:40:50,899: ERROR: 4284149673: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/4284149673.py", line 206, in train_test_splitting
    X_train = X_train.reset_index(drop=True)
AttributeError: 'numpy.ndarray' object has no attribute 'reset_index'
[2024-07-06 23:43:05,349: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:43:05,353: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:43:05,357: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:43:05,359: INFO: common: created directory at: artifacts]
[2024-07-06 23:43:05,360: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:43:06,281: ERROR: 4113180182: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/4113180182.py", line 206, in train_test_splitting
    X_train = X_train.to_frame().reset_index(drop=True)
AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'
[2024-07-06 23:47:25,731: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:47:25,735: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:47:25,744: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:47:25,746: INFO: common: created directory at: artifacts]
[2024-07-06 23:47:25,748: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:47:25,946: ERROR: 1660335642: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/1660335642.py", line 208, in train_test_splitting
    X_train = X_train.to_frame().reset_index(drop=True)
AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'
[2024-07-06 23:51:55,238: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:51:55,242: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:51:55,246: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:51:55,247: INFO: common: created directory at: artifacts]
[2024-07-06 23:51:55,250: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:51:55,316: ERROR: 3325183824: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/3325183824.py", line 210, in train_test_splitting
    X_train = X_train.to_frame().reset_index(drop=True)
AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'
[2024-07-06 23:53:08,994: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-06 23:53:08,997: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-06 23:53:09,002: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-06 23:53:09,004: INFO: common: created directory at: artifacts]
[2024-07-06 23:53:09,006: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-06 23:53:09,173: ERROR: 301219887: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/301219887.py", line 210, in train_test_splitting
    X_train = X_train.to_frame().reset_index(drop=True)
AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'
[2024-07-07 00:03:31,954: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:03:31,957: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:03:31,962: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:03:31,964: INFO: common: created directory at: artifacts]
[2024-07-07 00:03:31,966: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 00:03:33,506: ERROR: 2361764916: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/2361764916.py", line 216, in train_test_splitting
    train_processed = pd.concat([X_train, y_train], axis=1)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 448, in __init__
    ndims = self._get_ndims(objs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 489, in _get_ndims
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid
[2024-07-07 00:05:16,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:05:16,348: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:05:16,354: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:05:16,355: INFO: common: created directory at: artifacts]
[2024-07-07 00:05:16,357: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 00:05:17,291: ERROR: 1022419336: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_7478/1022419336.py", line 219, in train_test_splitting
    y_train_df = pd.DataFrame(y_train).to_frame().reset_index(drop=True)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_frame'
[2024-07-07 00:05:32,561: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:05:32,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:05:32,569: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:05:32,571: INFO: common: created directory at: artifacts]
[2024-07-07 00:05:32,572: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 00:05:33,612: INFO: 3323293472: Data split into training and test sets]
[2024-07-07 00:05:33,613: INFO: 3323293472: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 00:05:33,614: INFO: 3323293472: Shape of preprocessed test data: (480, 14)]
[2024-07-07 00:29:40,753: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 00:29:40,756: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:29:40,756: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:29:40,759: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:29:40,759: INFO: common: created directory at: artifacts]
[2024-07-07 00:29:40,759: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 00:29:40,760: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 00:29:40,788: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 00:29:40,788: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 00:29:40,792: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:29:40,793: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:29:40,798: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:29:40,798: INFO: common: created directory at: artifacts]
[2024-07-07 00:29:40,798: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 00:29:40,809: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 00:29:40,809: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 00:29:40,809: ERROR: main: name 'DataTransformationTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 36, in <module>
    obj = DataTransformationTrainingPipeline()
NameError: name 'DataTransformationTrainingPipeline' is not defined
[2024-07-07 00:42:47,190: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 00:42:47,192: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:42:47,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:42:47,195: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:42:47,196: INFO: common: created directory at: artifacts]
[2024-07-07 00:42:47,196: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 00:42:47,197: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 00:42:47,199: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 00:42:47,199: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 00:42:47,201: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:42:47,202: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:42:47,204: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:42:47,205: INFO: common: created directory at: artifacts]
[2024-07-07 00:42:47,205: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 00:42:47,215: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 00:42:47,215: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 00:42:47,219: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:42:47,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:42:47,223: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:42:47,224: INFO: common: created directory at: artifacts]
[2024-07-07 00:42:47,224: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 00:42:47,247: ERROR: main: name 'logger' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 217, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 195, in preprocess_data
    self._save_transformer(transformer)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 203, in _save_transformer
    joblib.dump(transformer, os.path.join(self.config.root_dir, self.config.preprocessor_name))
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 38, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/data_transformation_training.py", line 19, in main
    data_transformation.train_test_splitting()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 248, in train_test_splitting
    logger.error("An error occurred during train-test splitting", exc_info=True)
NameError: name 'logger' is not defined
[2024-07-07 00:43:38,088: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 00:43:38,090: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:43:38,091: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:43:38,094: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:43:38,094: INFO: common: created directory at: artifacts]
[2024-07-07 00:43:38,095: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 00:43:38,095: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 00:43:38,097: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 00:43:38,097: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 00:43:38,100: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:43:38,101: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:43:38,105: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:43:38,106: INFO: common: created directory at: artifacts]
[2024-07-07 00:43:38,106: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 00:43:38,491: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 00:43:38,492: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 00:43:38,501: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:43:38,503: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:43:38,506: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:43:38,506: INFO: common: created directory at: artifacts]
[2024-07-07 00:43:38,507: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 00:43:38,536: ERROR: data_transformation: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 218, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 196, in preprocess_data
    self._save_transformer(transformer)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 204, in _save_transformer
    joblib.dump(transformer, os.path.join(self.config.root_dir, self.config.preprocessor_name))
NameError: name 'os' is not defined
[2024-07-07 00:43:38,536: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 38, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/data_transformation_training.py", line 19, in main
    data_transformation.train_test_splitting()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 218, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 196, in preprocess_data
    self._save_transformer(transformer)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/data_transformation.py", line 204, in _save_transformer
    joblib.dump(transformer, os.path.join(self.config.root_dir, self.config.preprocessor_name))
NameError: name 'os' is not defined
[2024-07-07 00:43:56,425: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 00:43:56,428: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:43:56,429: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:43:56,431: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:43:56,432: INFO: common: created directory at: artifacts]
[2024-07-07 00:43:56,432: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 00:43:56,432: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 00:43:56,435: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 00:43:56,435: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 00:43:56,437: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:43:56,438: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:43:56,442: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:43:56,442: INFO: common: created directory at: artifacts]
[2024-07-07 00:43:56,442: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 00:43:56,453: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 00:43:56,454: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 00:43:56,457: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 00:43:56,457: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 00:43:56,461: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 00:43:56,461: INFO: common: created directory at: artifacts]
[2024-07-07 00:43:56,462: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 00:43:57,786: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 00:43:57,787: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 00:43:57,787: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 00:43:57,787: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 14:31:57,824: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 14:31:57,981: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 14:31:58,039: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 14:31:58,041: INFO: common: created directory at: artifacts]
[2024-07-07 14:32:34,479: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 14:32:34,482: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 14:32:34,486: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 14:32:34,488: INFO: common: created directory at: artifacts]
[2024-07-07 14:32:34,489: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 14:34:38,952: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 14:34:38,955: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 14:34:38,960: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 14:34:38,962: INFO: common: created directory at: artifacts]
[2024-07-07 14:34:38,964: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 15:26:55,456: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 15:26:55,458: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 15:26:55,463: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 15:26:55,465: INFO: common: created directory at: artifacts]
[2024-07-07 15:26:55,467: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 15:26:55,525: ERROR: 3390105472: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ownership'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_indexing.py", line 361, in _get_column_indices
    col_idx = all_columns.get_loc(col)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'ownership'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/ipykernel_13059/3390105472.py", line 150, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_13059/3390105472.py", line 138, in preprocess_data
    X_transformed = transformer.fit_transform(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 968, in fit_transform
    self._validate_column_callables(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 536, in _validate_column_callables
    transformer_to_input_indices[name] = _get_column_indices(X, columns)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_indexing.py", line 369, in _get_column_indices
    raise ValueError("A given column is not a column of the dataframe") from e
ValueError: A given column is not a column of the dataframe
[2024-07-07 15:28:29,811: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 15:28:29,817: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 15:28:29,826: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 15:28:29,829: INFO: common: created directory at: artifacts]
[2024-07-07 15:28:29,832: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 15:28:29,852: ERROR: 712126383: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'owsership'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_indexing.py", line 361, in _get_column_indices
    col_idx = all_columns.get_loc(col)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'owsership'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/ipykernel_13059/712126383.py", line 150, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_13059/712126383.py", line 138, in preprocess_data
    X_transformed = transformer.fit_transform(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 968, in fit_transform
    self._validate_column_callables(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 536, in _validate_column_callables
    transformer_to_input_indices[name] = _get_column_indices(X, columns)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_indexing.py", line 369, in _get_column_indices
    raise ValueError("A given column is not a column of the dataframe") from e
ValueError: A given column is not a column of the dataframe
[2024-07-07 15:29:02,900: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 15:29:02,904: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 15:29:02,912: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 15:29:02,913: INFO: common: created directory at: artifacts]
[2024-07-07 15:29:02,915: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 15:29:02,935: ERROR: 712126383: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'owsership'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_indexing.py", line 361, in _get_column_indices
    col_idx = all_columns.get_loc(col)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'owsership'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/ipykernel_13059/712126383.py", line 150, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_13059/712126383.py", line 138, in preprocess_data
    X_transformed = transformer.fit_transform(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 968, in fit_transform
    self._validate_column_callables(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 536, in _validate_column_callables
    transformer_to_input_indices[name] = _get_column_indices(X, columns)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_indexing.py", line 369, in _get_column_indices
    raise ValueError("A given column is not a column of the dataframe") from e
ValueError: A given column is not a column of the dataframe
[2024-07-07 15:29:50,827: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 15:29:50,830: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 15:29:50,835: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 15:29:50,837: INFO: common: created directory at: artifacts]
[2024-07-07 15:29:50,840: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 15:29:52,995: ERROR: 1131935452: An error occurred during train-test splitting]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 1310, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 532, in fit_transform
    routed_params = self._check_method_params(method="fit_transform", props=params)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 358, in _check_method_params
    **{
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 360, in <dictcomp>
    for name, step in self.steps
ValueError: too many values to unpack (expected 2)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/ipykernel_13059/1131935452.py", line 150, in train_test_splitting
    X, y = self.preprocess_data(data)
  File "/tmp/ipykernel_13059/1131935452.py", line 138, in preprocess_data
    X_transformed = transformer.fit_transform(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 976, in fit_transform
    result = self._call_func_on_transformers(
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 885, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 74, in __call__
    return super().__call__(iterable_with_config)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
ValueError: too many values to unpack (expected 2)
[2024-07-07 19:25:36,546: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:25:36,549: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:25:36,554: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:25:36,557: INFO: common: created directory at: artifacts]
[2024-07-07 19:25:36,560: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:25:36,575: ERROR: 4243739788: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_13059/4243739788.py", line 202, in train_test_splitting
    X, y = self.preprocess_data(data)
TypeError: DataTransformation.preprocess_data() missing 1 required positional argument: 'y'
[2024-07-07 19:26:01,523: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:26:01,527: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:26:01,531: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:26:01,533: INFO: common: created directory at: artifacts]
[2024-07-07 19:26:01,534: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:26:01,592: ERROR: 4082560514: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_13059/4082560514.py", line 214, in train_test_splitting
    X_train,y_train = self.preprocess_data(X_train,y_train)
  File "/tmp/ipykernel_13059/4082560514.py", line 178, in preprocess_data
    X_transformed = transformer.transform(X)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py", line 1035, in transform
    check_is_fitted(self)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1661, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
[2024-07-07 19:27:20,326: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:27:20,329: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:27:20,334: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:27:20,336: INFO: common: created directory at: artifacts]
[2024-07-07 19:27:20,340: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:27:26,739: ERROR: 2769446730: An error occurred during train-test splitting]
Traceback (most recent call last):
  File "/tmp/ipykernel_13059/2769446730.py", line 230, in train_test_splitting
    y_train_df = pd.DataFrame(y_train).to_frame().reset_index(drop=True)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_frame'
[2024-07-07 19:27:43,427: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:27:43,431: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:27:43,435: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:27:43,436: INFO: common: created directory at: artifacts]
[2024-07-07 19:27:43,437: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:27:44,790: INFO: 2513608790: Data split into training and test sets]
[2024-07-07 19:27:44,791: INFO: 2513608790: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 19:27:44,792: INFO: 2513608790: Shape of preprocessed test data: (480, 14)]
[2024-07-07 19:32:28,800: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:32:28,803: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:32:28,807: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:32:28,809: INFO: common: created directory at: artifacts]
[2024-07-07 19:32:28,810: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:32:29,350: INFO: 262633336: Data split into training and test sets]
[2024-07-07 19:32:29,351: INFO: 262633336: Shape of preprocessed training data: (1028, 15)]
[2024-07-07 19:32:29,352: INFO: 262633336: Shape of preprocessed test data: (480, 15)]
[2024-07-07 19:34:38,372: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:34:38,375: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:34:38,381: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:34:38,384: INFO: common: created directory at: artifacts]
[2024-07-07 19:34:38,387: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:34:38,555: INFO: 3257775251: Data split into training and test sets]
[2024-07-07 19:34:38,556: INFO: 3257775251: Shape of preprocessed training data: (1028, 15)]
[2024-07-07 19:34:38,557: INFO: 3257775251: Shape of preprocessed test data: (480, 15)]
[2024-07-07 19:35:14,253: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:35:14,255: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:35:14,260: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:35:14,261: INFO: common: created directory at: artifacts]
[2024-07-07 19:35:14,263: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:35:15,635: INFO: 1230018745: Data split into training and test sets]
[2024-07-07 19:35:15,636: INFO: 1230018745: Shape of preprocessed training data: (1028, 15)]
[2024-07-07 19:35:15,637: INFO: 1230018745: Shape of preprocessed test data: (480, 15)]
[2024-07-07 19:36:08,189: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:36:08,192: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:36:08,198: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:36:08,200: INFO: common: created directory at: artifacts]
[2024-07-07 19:36:08,201: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:36:08,532: INFO: 71699463: Data split into training and test sets]
[2024-07-07 19:36:08,532: INFO: 71699463: Shape of preprocessed training data: (1028, 15)]
[2024-07-07 19:36:08,533: INFO: 71699463: Shape of preprocessed test data: (480, 15)]
[2024-07-07 19:36:38,149: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:36:38,152: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:36:38,157: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:36:38,158: INFO: common: created directory at: artifacts]
[2024-07-07 19:36:38,159: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:36:38,375: INFO: 730129918: Data split into training and test sets]
[2024-07-07 19:36:38,389: INFO: 730129918: Shape of preprocessed training data: (1028, 15)]
[2024-07-07 19:36:38,391: INFO: 730129918: Shape of preprocessed test data: (480, 15)]
[2024-07-07 19:37:57,204: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:37:57,206: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:37:57,212: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:37:57,214: INFO: common: created directory at: artifacts]
[2024-07-07 19:37:57,217: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:37:57,620: INFO: 365662214: Data split into training and test sets]
[2024-07-07 19:37:57,621: INFO: 365662214: Shape of preprocessed training data: (1028, 15)]
[2024-07-07 19:37:57,622: INFO: 365662214: Shape of preprocessed test data: (480, 15)]
[2024-07-07 19:41:22,496: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:41:22,502: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:41:22,516: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:41:22,521: INFO: common: created directory at: artifacts]
[2024-07-07 19:41:22,527: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 19:41:22,656: INFO: 2589047956: Data split into training and test sets]
[2024-07-07 19:41:22,656: INFO: 2589047956: Shape of preprocessed training data: (813, 16)]
[2024-07-07 19:41:22,657: INFO: 2589047956: Shape of preprocessed test data: (272, 16)]
[2024-07-07 19:42:09,023: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 19:42:09,025: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 19:42:09,029: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 19:42:09,031: INFO: common: created directory at: artifacts]
[2024-07-07 19:42:09,032: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 20:08:56,116: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:08:56,119: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:08:56,120: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:08:56,122: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:08:56,122: INFO: common: created directory at: artifacts]
[2024-07-07 20:08:56,123: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:08:56,123: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:08:56,178: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:08:56,178: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:08:56,182: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:08:56,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:08:56,186: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:08:56,186: INFO: common: created directory at: artifacts]
[2024-07-07 20:08:56,186: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:08:56,216: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:08:56,216: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:08:56,219: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:08:56,220: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:08:56,223: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:08:56,223: INFO: common: created directory at: artifacts]
[2024-07-07 20:08:56,224: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:08:57,606: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:08:57,606: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:08:57,606: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:08:57,607: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:08:57,607: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:08:57,611: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:08:57,612: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:08:57,615: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:08:57,616: INFO: common: created directory at: artifacts]
[2024-07-07 20:08:57,616: ERROR: main: name 'DataValidation' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 16, in main
    model_trainer = DataValidation(config=model_trainer_config)
NameError: name 'DataValidation' is not defined
[2024-07-07 20:09:53,272: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:09:53,276: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:09:53,276: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:09:53,279: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:09:53,279: INFO: common: created directory at: artifacts]
[2024-07-07 20:09:53,279: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:09:53,279: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:09:53,281: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:09:53,281: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:09:53,286: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:09:53,287: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:09:53,290: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:09:53,290: INFO: common: created directory at: artifacts]
[2024-07-07 20:09:53,291: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:09:53,301: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:09:53,301: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:09:53,307: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:09:53,308: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:09:53,310: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:09:53,311: INFO: common: created directory at: artifacts]
[2024-07-07 20:09:53,311: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:09:54,716: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:09:54,716: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:09:54,717: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:09:54,717: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:09:54,717: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:09:54,721: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:09:54,721: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:09:54,724: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:09:54,725: INFO: common: created directory at: artifacts]
[2024-07-07 20:09:54,725: ERROR: main: 'ModelTrainer' object has no attribute 'train_test_splitting']
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train_test_splitting()
AttributeError: 'ModelTrainer' object has no attribute 'train_test_splitting'
[2024-07-07 20:10:27,058: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:10:27,061: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:10:27,062: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:10:27,064: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:10:27,064: INFO: common: created directory at: artifacts]
[2024-07-07 20:10:27,064: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:10:27,065: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:10:27,067: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:10:27,067: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:10:27,069: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:10:27,070: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:10:27,073: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:10:27,074: INFO: common: created directory at: artifacts]
[2024-07-07 20:10:27,074: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:10:27,083: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:10:27,084: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:10:27,087: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:10:27,088: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:10:27,090: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:10:27,091: INFO: common: created directory at: artifacts]
[2024-07-07 20:10:27,091: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:10:28,472: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:10:28,472: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:10:28,472: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:10:28,472: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:10:28,473: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:10:28,476: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:10:28,477: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:10:28,481: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:10:28,481: INFO: common: created directory at: artifacts]
[2024-07-07 20:10:28,481: ERROR: main: 'function' object has no attribute 'train_data_path']
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 11, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-07-07 20:12:30,801: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:12:30,804: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:12:30,804: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:12:30,807: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:12:30,808: INFO: common: created directory at: artifacts]
[2024-07-07 20:12:30,808: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:12:30,808: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:12:30,810: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:12:30,810: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:12:30,815: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:12:30,816: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:12:30,821: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:12:30,821: INFO: common: created directory at: artifacts]
[2024-07-07 20:12:30,821: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:12:30,854: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:12:30,854: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:12:30,858: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:12:30,859: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:12:30,862: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:12:30,862: INFO: common: created directory at: artifacts]
[2024-07-07 20:12:30,862: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:12:32,274: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:12:32,274: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:12:32,274: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:12:32,274: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:12:32,274: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:12:32,278: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:12:32,280: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:12:32,283: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:12:32,284: INFO: common: created directory at: artifacts]
[2024-07-07 20:12:32,284: ERROR: main: 'function' object has no attribute 'train_data_path']
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 11, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-07-07 20:13:52,223: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:13:52,226: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:13:52,227: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:13:52,229: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:13:52,230: INFO: common: created directory at: artifacts]
[2024-07-07 20:13:52,230: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:13:52,230: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:13:52,232: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:13:52,232: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:13:52,235: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:13:52,236: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:13:52,239: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:13:52,239: INFO: common: created directory at: artifacts]
[2024-07-07 20:13:52,239: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:13:52,249: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:13:52,250: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:13:52,253: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:13:52,253: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:13:52,256: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:13:52,256: INFO: common: created directory at: artifacts]
[2024-07-07 20:13:52,256: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:13:53,746: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:13:53,746: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:13:53,747: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:13:53,747: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:13:53,748: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:13:53,760: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:13:53,762: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:13:53,769: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:13:53,770: INFO: common: created directory at: artifacts]
[2024-07-07 20:13:53,770: ERROR: main: 'function' object has no attribute 'train_data_path']
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 12, in train
    print("train data path ",self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-07-07 20:14:18,497: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:14:18,501: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:14:18,501: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:14:18,504: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:14:18,504: INFO: common: created directory at: artifacts]
[2024-07-07 20:14:18,504: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:14:18,504: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:14:18,507: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:14:18,507: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:14:18,510: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:14:18,511: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:14:18,514: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:14:18,514: INFO: common: created directory at: artifacts]
[2024-07-07 20:14:18,514: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:14:18,524: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:14:18,524: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:14:18,530: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:14:18,531: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:14:18,534: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:14:18,534: INFO: common: created directory at: artifacts]
[2024-07-07 20:14:18,534: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:14:19,919: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:14:19,919: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:14:19,920: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:14:19,920: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:14:19,920: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:14:19,925: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:14:19,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:14:19,929: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:14:19,930: INFO: common: created directory at: artifacts]
[2024-07-07 20:14:19,930: ERROR: main: 'function' object has no attribute 'train_data_path']
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 13, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-07-07 20:15:48,932: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:15:48,935: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:15:48,936: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:15:48,938: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:15:48,939: INFO: common: created directory at: artifacts]
[2024-07-07 20:15:48,939: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:15:48,939: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:15:48,941: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:15:48,941: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:15:48,944: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:15:48,945: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:15:48,948: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:15:48,948: INFO: common: created directory at: artifacts]
[2024-07-07 20:15:48,949: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:15:48,959: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:15:48,959: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:15:48,965: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:15:48,966: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:15:48,968: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:15:48,968: INFO: common: created directory at: artifacts]
[2024-07-07 20:15:48,969: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:15:50,389: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:15:50,389: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:15:50,389: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:15:50,390: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:15:50,390: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:15:50,396: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:15:50,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:15:50,403: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:15:50,403: INFO: common: created directory at: artifacts]
[2024-07-07 20:15:50,404: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 20:15:50,412: ERROR: main: name 'RandomForestRegressor' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 22, in train
    rf_rgrs = RandomForestRegressor(n_estimators=self.config.n_estimators)
NameError: name 'RandomForestRegressor' is not defined
[2024-07-07 20:16:34,576: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:16:34,579: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:16:34,580: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:16:34,582: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:16:34,582: INFO: common: created directory at: artifacts]
[2024-07-07 20:16:34,582: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:16:34,583: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:16:34,585: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:16:34,585: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:16:34,588: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:16:34,589: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:16:34,592: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:16:34,592: INFO: common: created directory at: artifacts]
[2024-07-07 20:16:34,592: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:16:34,602: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:16:34,603: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:16:34,605: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:16:34,606: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:16:34,609: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:16:34,609: INFO: common: created directory at: artifacts]
[2024-07-07 20:16:34,609: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:16:35,972: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:16:35,973: INFO: data_transformation: Shape of preprocessed training data: (1028, 14)]
[2024-07-07 20:16:35,973: INFO: data_transformation: Shape of preprocessed test data: (480, 14)]
[2024-07-07 20:16:35,973: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:16:35,973: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:16:35,977: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:16:35,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:16:35,981: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:16:35,982: INFO: common: created directory at: artifacts]
[2024-07-07 20:16:35,982: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 20:16:35,996: ERROR: main: Input y contains NaN.]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 24, in train
    rf_rgrs.fit(train_x, train_y)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1318, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1328, in _check_y
    y = check_array(
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input y contains NaN.
[2024-07-07 20:17:35,287: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:17:35,290: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:35,291: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:35,294: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:35,294: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:35,294: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:17:35,295: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:17:35,297: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:17:35,297: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:17:35,300: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:35,301: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:35,303: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:35,304: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:35,304: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:17:35,316: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:17:35,316: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:17:35,319: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:35,320: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:35,323: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:35,323: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:35,324: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:17:36,714: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:17:36,714: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-07 20:17:36,715: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-07 20:17:36,715: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:17:36,715: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:17:36,719: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:36,720: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:36,725: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:36,725: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:36,725: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 20:17:37,087: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 49, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_trainer_training.py", line 17, in main
    model_trainer.train()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_trainer.py", line 26, in train
    joblib.dump(rf_rgrs, os.path.join(self.config.root_dir, self.config.model_name))
NameError: name 'os' is not defined
[2024-07-07 20:17:56,219: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-07 20:17:56,222: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:56,223: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:56,225: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:56,225: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:56,226: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-07 20:17:56,226: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-07 20:17:56,227: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-07 20:17:56,228: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-07 20:17:56,231: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:56,232: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:56,235: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:56,236: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:56,236: INFO: common: created directory at: artifacts/data_validation]
[2024-07-07 20:17:56,246: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-07 20:17:56,246: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-07 20:17:56,249: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:56,250: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:56,255: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:56,255: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:56,255: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-07 20:17:57,644: INFO: data_transformation: Data split into training and test sets]
[2024-07-07 20:17:57,644: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-07 20:17:57,644: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-07 20:17:57,645: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-07 20:17:57,645: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-07 20:17:57,649: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-07 20:17:57,650: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-07 20:17:57,653: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-07 20:17:57,653: INFO: common: created directory at: artifacts]
[2024-07-07 20:17:57,654: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-07 20:17:58,058: INFO: main: >>>>>> stage model Training stage completed <<<<<<

x==========x]
[2024-07-09 17:59:52,907: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 17:59:53,106: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 17:59:53,152: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 17:59:53,172: INFO: common: created directory at: artifacts]
[2024-07-09 17:59:53,179: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 18:00:56,121: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 18:00:56,125: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 18:00:56,130: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 18:00:56,132: INFO: common: created directory at: artifacts]
[2024-07-09 18:00:56,135: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 18:03:01,980: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 18:03:01,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 18:03:01,988: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 18:03:01,989: INFO: common: created directory at: artifacts]
[2024-07-09 18:03:01,990: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 18:04:17,857: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 18:04:17,860: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 18:04:17,865: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 18:04:17,867: INFO: common: created directory at: artifacts]
[2024-07-09 18:04:17,868: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 18:04:18,571: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2024-07-09 19:01:58,134: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-09 19:01:58,242: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:01:58,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:01:58,316: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:01:58,316: INFO: common: created directory at: artifacts]
[2024-07-09 19:01:58,317: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-09 19:01:58,317: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-09 19:01:58,413: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-09 19:01:58,414: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-09 19:01:58,429: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:01:58,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:01:58,442: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:01:58,443: INFO: common: created directory at: artifacts]
[2024-07-09 19:01:58,444: INFO: common: created directory at: artifacts/data_validation]
[2024-07-09 19:01:58,501: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-09 19:01:58,502: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-09 19:01:58,519: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:01:58,521: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:01:58,528: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:01:58,529: INFO: common: created directory at: artifacts]
[2024-07-09 19:01:58,529: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-09 19:02:00,522: INFO: data_transformation: Data split into training and test sets]
[2024-07-09 19:02:00,522: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-09 19:02:00,522: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-09 19:02:00,522: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-09 19:02:00,523: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-09 19:02:00,528: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:02:00,529: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:02:00,531: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:02:00,532: INFO: common: created directory at: artifacts]
[2024-07-09 19:02:00,532: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-09 19:02:01,202: INFO: main: >>>>>> stage model Training stage completed <<<<<<

x==========x]
[2024-07-09 19:02:01,202: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2024-07-09 19:02:01,202: ERROR: main: name 'ModelEvaluationPipeline' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 59, in <module>
    obj = ModelEvaluationPipeline()
NameError: name 'ModelEvaluationPipeline' is not defined
[2024-07-09 19:02:41,931: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-09 19:02:41,941: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:02:41,943: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:02:41,948: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:02:41,948: INFO: common: created directory at: artifacts]
[2024-07-09 19:02:41,948: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-09 19:02:41,949: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-09 19:02:41,952: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-09 19:02:41,952: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-09 19:02:41,960: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:02:41,961: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:02:41,964: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:02:41,965: INFO: common: created directory at: artifacts]
[2024-07-09 19:02:41,965: INFO: common: created directory at: artifacts/data_validation]
[2024-07-09 19:02:41,979: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-09 19:02:41,979: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-09 19:02:41,985: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:02:41,986: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:02:41,989: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:02:41,989: INFO: common: created directory at: artifacts]
[2024-07-09 19:02:41,989: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-09 19:02:43,343: INFO: data_transformation: Data split into training and test sets]
[2024-07-09 19:02:43,343: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-09 19:02:43,343: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-09 19:02:43,344: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-09 19:02:43,344: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-09 19:02:43,350: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:02:43,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:02:43,354: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:02:43,355: INFO: common: created directory at: artifacts]
[2024-07-09 19:02:43,355: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-09 19:02:43,776: INFO: main: >>>>>> stage model Training stage completed <<<<<<

x==========x]
[2024-07-09 19:02:43,776: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2024-07-09 19:02:43,790: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:02:43,792: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:02:43,797: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:02:43,798: INFO: common: created directory at: artifacts]
[2024-07-09 19:02:43,798: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 19:02:45,679: ERROR: main: name 'save_json' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 62, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_evaluation_training.py", line 17, in main
    model_evaluation.log_into_mlflow()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_evaluation.py", line 47, in log_into_mlflow
    save_json(path=Path(self.config.metric_file_name), data=scores)
NameError: name 'save_json' is not defined
[2024-07-09 19:04:31,203: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-09 19:04:31,207: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:31,207: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:31,210: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:31,210: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:31,210: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-09 19:04:31,210: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-09 19:04:31,212: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-09 19:04:31,212: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-09 19:04:31,216: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:31,217: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:31,220: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:31,220: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:31,220: INFO: common: created directory at: artifacts/data_validation]
[2024-07-09 19:04:31,231: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-09 19:04:31,232: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-09 19:04:31,236: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:31,237: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:31,240: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:31,240: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:31,240: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-09 19:04:32,643: INFO: data_transformation: Data split into training and test sets]
[2024-07-09 19:04:32,644: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-09 19:04:32,644: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-09 19:04:32,645: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-09 19:04:32,645: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-09 19:04:32,654: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:32,655: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:32,660: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:32,661: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:32,661: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-09 19:04:33,152: INFO: main: >>>>>> stage model Training stage completed <<<<<<

x==========x]
[2024-07-09 19:04:33,152: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2024-07-09 19:04:33,163: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:33,165: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:33,170: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:33,170: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:33,171: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 19:04:33,601: ERROR: main: name 'Path' is not defined]
Traceback (most recent call last):
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/main.py", line 62, in <module>
    obj.main()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/pipeline/model_evaluation_training.py", line 17, in main
    model_evaluation.log_into_mlflow()
  File "/home/reby/Desktop/personal_Projects/car_price_prediction/src/carPricePrediction/components/model_evaluation.py", line 48, in log_into_mlflow
    save_json(path=Path(self.config.metric_file_name), data=scores)
NameError: name 'Path' is not defined
[2024-07-09 19:04:57,797: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-09 19:04:57,801: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:57,801: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:57,804: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:57,804: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:57,804: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-09 19:04:57,804: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-09 19:04:57,806: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-09 19:04:57,806: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-09 19:04:57,811: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:57,812: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:57,815: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:57,816: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:57,816: INFO: common: created directory at: artifacts/data_validation]
[2024-07-09 19:04:57,827: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-09 19:04:57,827: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-09 19:04:57,832: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:57,833: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:57,836: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:57,836: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:57,836: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-09 19:04:59,240: INFO: data_transformation: Data split into training and test sets]
[2024-07-09 19:04:59,240: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-09 19:04:59,241: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-09 19:04:59,241: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-09 19:04:59,242: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-09 19:04:59,250: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:59,251: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:59,255: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:59,255: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:59,255: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-09 19:04:59,683: INFO: main: >>>>>> stage model Training stage completed <<<<<<

x==========x]
[2024-07-09 19:04:59,684: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2024-07-09 19:04:59,687: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-09 19:04:59,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-09 19:04:59,690: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-09 19:04:59,691: INFO: common: created directory at: artifacts]
[2024-07-09 19:04:59,691: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-09 19:05:00,531: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2024-07-09 19:05:07,924: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2024-07-10 00:19:56,981: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 00:19:57,023: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 00:20:00,127: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:20:00] "GET / HTTP/1.1" 200 -]
[2024-07-10 00:20:00,611: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:20:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-07-10 00:20:02,821: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:20:02] "GET / HTTP/1.1" 200 -]
[2024-07-10 00:20:09,816: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:20:09] "[33mGET /train HTTP/1.1[0m" 404 -]
[2024-07-10 00:20:18,226: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:20:18] "GET / HTTP/1.1" 200 -]
[2024-07-10 00:36:36,287: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:36:36] "GET /?insurance_validity=Comprehensive&fuelType=Petrol&fuelType=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=10000&mileage_kmpl=12&engine_cc=40000&torque_nm=150 HTTP/1.1" 200 -]
[2024-07-10 00:37:09,237: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:37:09] "GET / HTTP/1.1" 200 -]
[2024-07-10 00:37:26,639: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:37:26] "GET /?insurance_validity=Comprehensive&fuelType=Petrol&fuelType=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=100000&mileage_kmpl=12&engine_cc=40000&torque_nm=1234 HTTP/1.1" 200 -]
[2024-07-10 00:40:12,518: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:40:12] "GET /?insurance_validity=Comprehensive&fuelType=Petrol&fuelType=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=100000&mileage_kmpl=12&engine_cc=40000&torque_nm=1234 HTTP/1.1" 200 -]
[2024-07-10 00:40:28,310: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:40:28] "GET /?insurance_validity=Comprehensive&fuelType=Petrol&fuelType=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=100000&mileage_kmpl=12&engine_cc=4000&torque_nm=1234 HTTP/1.1" 200 -]
[2024-07-10 00:41:12,728: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 00:41:12,728: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 00:41:12,738: INFO: _internal:  * Restarting with stat]
[2024-07-10 00:41:13,391: WARNING: _internal:  * Debugger is active!]
[2024-07-10 00:41:13,825: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 00:41:20,654: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:41:20] "GET / HTTP/1.1" 200 -]
[2024-07-10 00:41:32,685: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:41:32] "GET /?insurance_validity=Comprehensive&fuelType=Petrol&ownership=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=12356&mileage_kmpl=52636&engine_cc=332&torque_nm=6563 HTTP/1.1" 200 -]
[2024-07-10 00:42:31,931: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:42:31] "GET /predict HTTP/1.1" 200 -]
[2024-07-10 00:43:16,808: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 00:43:16,956: INFO: _internal:  * Restarting with stat]
[2024-07-10 00:43:17,664: WARNING: _internal:  * Debugger is active!]
[2024-07-10 00:43:17,665: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 00:43:19,511: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:43:19] "GET /predict HTTP/1.1" 200 -]
[2024-07-10 00:43:21,786: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 00:43:21,957: INFO: _internal:  * Restarting with stat]
[2024-07-10 00:43:22,812: WARNING: _internal:  * Debugger is active!]
[2024-07-10 00:43:22,813: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 00:43:32,557: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:43:32] "GET /predict?insurance_validity=Comprehensive&fuelType=Petrol&ownership=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=1234&mileage_kmpl=55145&engine_cc=316161&torque_nm=66 HTTP/1.1" 200 -]
[2024-07-10 00:49:14,378: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 00:49:14,378: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 00:49:14,379: INFO: _internal:  * Restarting with stat]
[2024-07-10 00:49:15,062: WARNING: _internal:  * Debugger is active!]
[2024-07-10 00:49:15,062: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 00:49:17,825: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:49:17] "GET / HTTP/1.1" 200 -]
[2024-07-10 00:53:44,813: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 00:53:44] "GET /predict?insurance_validity=Comprehensive&fuelType=Petrol&ownership=First+Owner&fuelType=Automatic&short_carname=Mercedes-Benz+S-Class&manufacturing_year=2014&seats=4&kms_driven=1234&mileage_kmpl=55145&engine_cc=316161&torque_nm=66 HTTP/1.1" 200 -]
[2024-07-10 01:10:07,842: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:10:07] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:10:22,924: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:10:22] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:11:23,357: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:11:23,485: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:11:24,281: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:11:24,282: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:11:28,470: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:11:28] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:12:38,949: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:12:39,099: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:12:39,788: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:12:39,789: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:12:44,739: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:12:44] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:16:19,837: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:16:19,970: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:16:20,657: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:16:20,657: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:16:28,411: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:16:28] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:16:38,088: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:16:38] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:20:19,474: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:20:19,601: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:20:20,358: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:20:20,359: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:20:35,642: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:20:35] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:20:49,112: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:20:49,227: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:20:49,982: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:20:49,983: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:20:53,258: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:20:53] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:21:23,986: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:21:24,108: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:21:24,803: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:21:24,804: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:21:29,443: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:21:29] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:22:17,063: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:22:17,193: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:22:17,891: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:22:17,891: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:22:26,071: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:22:26,189: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:22:26,870: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:22:26,871: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:22:31,815: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:22:31] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:22:44,250: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:22:44,411: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:22:45,078: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:22:45,079: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:22:50,108: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:22:50] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:23:13,913: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:23:14,065: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:23:14,806: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:23:14,807: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:23:18,407: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:23:18] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:25:31,678: INFO: _internal:  * Detected change in '/home/reby/Desktop/personal_Projects/car_price_prediction/app.py', reloading]
[2024-07-10 01:25:31,800: INFO: _internal:  * Restarting with stat]
[2024-07-10 01:25:32,543: WARNING: _internal:  * Debugger is active!]
[2024-07-10 01:25:32,543: INFO: _internal:  * Debugger PIN: 126-141-426]
[2024-07-10 01:25:36,695: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:25:36] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:27:08,347: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 01:27:08,347: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 01:27:12,074: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:27:12] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:27:22,845: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:27:22] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:28:50,011: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:28:50] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:29:04,396: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:29:04] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:29:19,643: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:29:19] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:29:23,743: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:29:23] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:30:22,532: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:30:22] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:30:36,755: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 01:30:36,755: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 01:30:39,137: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:30:39] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:30:50,882: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:30:50] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:42:10,966: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:42:10] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:42:47,674: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:42:47] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:43:05,231: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 01:43:05,231: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 01:43:19,175: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 01:43:19,175: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 01:43:28,183: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:43:28] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:43:38,083: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:43:38] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:45:23,420: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 01:45:23,420: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 01:45:37,092: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:45:37] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:45:48,569: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:45:48] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:48:06,241: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:48:06] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:48:12,129: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:48:12] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:50:19,537: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:50:19] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:50:33,985: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:50:33] "GET / HTTP/1.1" 200 -]
[2024-07-10 01:50:41,728: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:50:41] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 01:53:04,888: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 01:53:04] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 02:07:30,808: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 02:07:30,809: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 02:07:36,909: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:07:36] "GET / HTTP/1.1" 200 -]
[2024-07-10 02:07:47,148: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:07:47] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 02:08:31,209: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 02:08:31,209: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 02:08:39,340: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:08:39] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 02:08:49,089: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 02:08:49,089: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 02:08:53,041: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:08:53] "GET / HTTP/1.1" 200 -]
[2024-07-10 02:09:02,638: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:09:02] "POST /predict HTTP/1.1" 200 -]
[2024-07-10 02:11:24,433: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-07-10 02:11:24,433: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-10 02:11:27,349: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:11:27] "GET / HTTP/1.1" 200 -]
[2024-07-10 02:11:35,308: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-10 02:11:35,319: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-10 02:11:35,365: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 02:11:35,390: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-10 02:11:35,391: INFO: common: created directory at: artifacts]
[2024-07-10 02:11:35,391: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-10 02:11:35,391: INFO: data_ingestion: File already exists of size: ~ 27 KB]
[2024-07-10 02:11:35,439: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-10 02:11:35,440: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-07-10 02:11:35,446: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-10 02:11:35,448: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 02:11:35,451: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-10 02:11:35,451: INFO: common: created directory at: artifacts]
[2024-07-10 02:11:35,452: INFO: common: created directory at: artifacts/data_validation]
[2024-07-10 02:11:35,469: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-07-10 02:11:35,469: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-10 02:11:35,476: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-10 02:11:35,477: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 02:11:35,480: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-10 02:11:35,481: INFO: common: created directory at: artifacts]
[2024-07-10 02:11:35,481: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-10 02:11:37,471: INFO: data_transformation: Data split into training and test sets]
[2024-07-10 02:11:37,472: INFO: data_transformation: Shape of preprocessed training data: (813, 14)]
[2024-07-10 02:11:37,473: INFO: data_transformation: Shape of preprocessed test data: (272, 14)]
[2024-07-10 02:11:37,474: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-10 02:11:37,475: INFO: main: >>>>>> stage model Training stage started <<<<<<]
[2024-07-10 02:11:37,488: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-10 02:11:37,489: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 02:11:37,494: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-10 02:11:37,495: INFO: common: created directory at: artifacts]
[2024-07-10 02:11:37,495: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-10 02:11:38,284: INFO: main: >>>>>> stage model Training stage completed <<<<<<

x==========x]
[2024-07-10 02:11:38,285: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2024-07-10 02:11:38,292: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-10 02:11:38,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 02:11:38,297: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-07-10 02:11:38,298: INFO: common: created directory at: artifacts]
[2024-07-10 02:11:38,298: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-10 02:11:39,305: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2024-07-10 02:11:45,079: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2024-07-10 02:11:46,059: INFO: _internal: 127.0.0.1 - - [10/Jul/2024 02:11:46] "GET /train HTTP/1.1" 200 -]
